server:
  port: 8071

spring:
  application:
    name: spring cloud

  profiles:
    active: native
  cloud:
    config:
      server:
        prefix: /config
        git:
          uri: https://github.com/RewanshChoudhary/Dummy.git
          clone-on-start: true
          default-label: main
          force-pull: true

encrypt:
  key: mySecretKeyForDemo123

management:
  endpoints:
    web:
      exposure:
        include: "*"
